## Documentation: https://docs.travis-ci.com/user/languages/julia/
## Technical details: https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/julia.rb
language: julia
os:
  - linux
  #- osx
julia:
  - 1.0
  - nightly
notifications:
  email: false

codecov: true   # Note: this applies to Julia only; for C++ code in Polymake, more will need to be done
coveralls: true  # Note: this applies to Julia only; for C++ code in Polymake, more will need to be done

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Polymake"); Pkg.test("Polymake"; coverage=true)'

#
#after_success:
#  # push coverage results to Coveralls
#  - julia -e 'cd(Pkg.dir("Polymake")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
#  # push coverage results to Codecov
#  - julia -e 'cd(Pkg.dir("Polymake")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
